location: .gitman
sources:
  - repo: https://github.com/TimLakemann/ami.git
    name: ami
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: include/ami
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/TimLakemann/ami.git
    name: ami
    rev: f9b44c56297effa62badf9cab835b06a6528e074
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: include/ami
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
